set shell=bash
set relativenumber
set ruler
syntax on
colorscheme solarized
set background=dark
if has("mac")
  set gfn=Monaco:h14
end
set t_Co=256 " Explicitly tell vim that the terminal supports 256 colours

" Set encoding
set encoding=utf-8

" Whitespace stuff
set nowrap
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smarttab
set copyindent
set pastetoggle=<F2> " Disable auto-indenting magic for pasting
set shiftround
set list listchars=tab:→\ ,trail:·

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" No arrow keys!
map <Left> :echo "STOP IT!"<cr>
map <Right> :echo "STOP IT!"<cr>
map <Down> :echo "STOP IT!"<cr>
map <Up> :echo "STOP IT!"<cr>

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*,*.pyc,env-*/*,*.jpg,*.jpeg,*.gif,*.png,*.zip

" Status bar
set laststatus=2

if has("gui_running")
  if has('mac')
    " set fullscreen
    set fuoptions=maxvert,maxhorz ",background:#00AAaaaa
  endif
endif

" Highlight the current line
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
autocmd WinEnter * setlocal colorcolumn=80,100
autocmd WinLeave * setlocal colorcolumn=

" Set HTML as HTML-Django
au BufRead,BufNewFile *.html set ft=htmldjango

" vundlerc is a vim file
au BufRead,BufNewFile vundlerc set ft=vim

" Set less filetype
au BufNewFile,BufRead *.less set filetype=less

" Thorfile, Rakefile, Vagrantfile and Gemfile are Ruby
au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru} set ft=ruby

" add json syntax highlighting
au BufNewFile,BufRead *.json set ft=javascript

set backspace=indent,eol,start " allow backspacing over everything in insert mode
set autoread

" Yank to the OS X clipboard
noremap <leader>y "*y
noremap <leader>yy "*Y

" Directories for swp files
set backupdir=~/.dotfiles/vim/backup
set directory=~/.dotfiles/vim/backup

" Show (partial) command in the status line
set showcmd

imap <C-l> <Space>=><Space>
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

" Tabs
nmap <silent> <C-w>[ :tabp<cr>
nmap <silent> <C-w>] :tabn<cr>

" Clear search
nmap <silent> <cr> :nohlsearch<CR>

" Allow :w!! to sudo save
cmap w!! w !sudo tee % >/dev/null

" Vimrc management
nnoremap <leader>rs :source ~/.vimrc<CR>
nnoremap <leader>rt :tabnew ~/.dotfiles/vim/vimrc<CR>
nnoremap <leader>re :e ~/.dotfiles/vim/vimrc<CR>
nnoremap <leader>rd :e ~/.dotfiles/vim/ <CR>

" Esc
map ,, <C-^>
inoremap ;; <Esc>
