export EDITOR=vim
export VISUAL=vim
export GIT_EDITOR=vim

. ~/.dotfiles/zsh/aliases.zsh
. ~/.dotfiles/zsh/funcs.zsh

if [[ -a ~/.dotfiles/zsh/local.zsh ]]; then
  . ~/.dotfiles/zsh/local.zsh
fi

alias rm="rm" # Apparently someone decided to be helpful and make this `rm -i`.

# Don't logout on ctrl-d.
setopt IGNORE_EOF
