# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="mstriemer"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git github rails rails3 vi-mode brew rvm)

source $ZSH/oh-my-zsh.sh

export PATH=/usr/local/bin:$PATH
export EDITOR=vim
export GIT_EDITOR=vim

set -o vi

. ~/.dotfiles/zsh/aliases.zsh

if [[ -a ~/.dotfiles/zsh/local.zsh ]]; then
  . ~/.dotfiles/zsh/local.zsh
fi

# Customize to your needs...
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

function workon {
    if [[ $1 == "." ]]; then
        env_name=${PWD##*/}
    else
        env_name=$1
    fi
    source $HOME/.virtualenvs/$env_name/bin/activate
}
